language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo 'no installation required'

before_script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

script:
  - docker tag udagram-api-feed lanre039/udagram-api-feed:v2
  - docker tag udagram-api-user lanre039/udagram-api-user:v2
  - docker tag udagram-frontend lanre039/udagram-frontend:v5
  - docker tag udagram-reverseproxy lanre039/reverseproxy:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lanre039/udagram-api-feed:v2
  - docker push lanre039/udagram-api-user:v2
  - docker push lanre039/udagram-frontend:v5
  - docker push lanre039/reverseproxy:v2
