apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    run: udagram-api-feed
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    run: udagram-api-feed
